/**
 * BASE DE DATOS DE PAÍSES Y TIERS
 * Basado en los archivos CSV proporcionados.
 */
import type { Country } from '../types';

export const COUNTRY_DB = [
    // --- TIER 1 (High Revenue ~0.0035 - 0.0055) ---
    { name: 'South Korea', rate: 0.0055, tier: 1 as const, code: 'KR', region: 'Asia' },
    { name: 'Switzerland', rate: 0.0052, tier: 1 as const, code: 'CH', region: 'Europe' },
    { name: 'United Kingdom', rate: 0.0045, tier: 1 as const, code: 'GB', region: 'Europe' },
    { name: 'Norway', rate: 0.0045, tier: 1 as const, code: 'NO', region: 'Europe' },
    { name: 'United States', rate: 0.0042, tier: 1 as const, code: 'US', region: 'North America' },
    { name: 'Denmark', rate: 0.0041, tier: 1 as const, code: 'DK', region: 'Europe' },
    { name: 'Ireland', rate: 0.0040, tier: 1 as const, code: 'IE', region: 'Europe' },
    { name: 'Australia', rate: 0.0040, tier: 1 as const, code: 'AU', region: 'Oceania' },
    { name: 'New Zealand', rate: 0.0039, tier: 1 as const, code: 'NZ', region: 'Oceania' },
    { name: 'Canada', rate: 0.0038, tier: 1 as const, code: 'CA', region: 'North America' },
    { name: 'Sweden', rate: 0.0038, tier: 1 as const, code: 'SE', region: 'Europe' },
    { name: 'Netherlands', rate: 0.0037, tier: 1 as const, code: 'NL', region: 'Europe' },
    { name: 'Germany', rate: 0.0036, tier: 1 as const, code: 'DE', region: 'Europe' },
    { name: 'France', rate: 0.0035, tier: 1 as const, code: 'FR', region: 'Europe' },

    // --- TIER 2 (Med-High ~0.0025 - 0.0034) ---
    { name: 'Belgium', rate: 0.0034, tier: 2 as const, code: 'BE', region: 'Europe' },
    { name: 'Austria', rate: 0.0034, tier: 2 as const, code: 'AT', region: 'Europe' },
    { name: 'Finland', rate: 0.0033, tier: 2 as const, code: 'FI', region: 'Europe' },
    { name: 'Monaco', rate: 0.0033, tier: 2 as const, code: 'MC', region: 'Europe' },
    { name: 'Liechtenstein', rate: 0.0033, tier: 2 as const, code: 'LI', region: 'Europe' },
    { name: 'Iceland', rate: 0.0032, tier: 2 as const, code: 'IS', region: 'Europe' },
    { name: 'Luxembourg', rate: 0.0032, tier: 2 as const, code: 'LU', region: 'Europe' },
    { name: 'Italy', rate: 0.0029, tier: 2 as const, code: 'IT', region: 'Europe' },
    { name: 'Spain', rate: 0.0028, tier: 2 as const, code: 'ES', region: 'Europe' },
    { name: 'Andorra', rate: 0.0028, tier: 2 as const, code: 'AD', region: 'Europe' },
    { name: 'Japan', rate: 0.0028, tier: 2 as const, code: 'JP', region: 'Asia' },
    { name: 'Israel', rate: 0.0027, tier: 2 as const, code: 'IL', region: 'Middle East' },
    { name: 'Singapore', rate: 0.0026, tier: 2 as const, code: 'SG', region: 'Asia' },
    { name: 'United Arab Emirates', rate: 0.0026, tier: 2 as const, code: 'AE', region: 'Middle East' },

    // --- TIER 3 (Medium ~0.0018 - 0.0024) ---
    { name: 'Taiwan', rate: 0.0024, tier: 3 as const, code: 'TW', region: 'Asia' },
    { name: 'Hong Kong', rate: 0.0024, tier: 3 as const, code: 'HK', region: 'Asia' },
    { name: 'Portugal', rate: 0.0021, tier: 3 as const, code: 'PT', region: 'Europe' },
    { name: 'Greece', rate: 0.0021, tier: 3 as const, code: 'GR', region: 'Europe' },
    { name: 'Cyprus', rate: 0.0021, tier: 3 as const, code: 'CY', region: 'Europe' },
    { name: 'Malta', rate: 0.0020, tier: 3 as const, code: 'MT', region: 'Europe' },
    { name: 'Estonia', rate: 0.0020, tier: 3 as const, code: 'EE', region: 'Europe' },
    { name: 'Latvia', rate: 0.0020, tier: 3 as const, code: 'LV', region: 'Europe' },
    { name: 'Lithuania', rate: 0.0020, tier: 3 as const, code: 'LT', region: 'Europe' },
    { name: 'Saudi Arabia', rate: 0.0020, tier: 3 as const, code: 'SA', region: 'Middle East' },
    { name: 'Qatar', rate: 0.0020, tier: 3 as const, code: 'QA', region: 'Middle East' },
    { name: 'Kuwait', rate: 0.0019, tier: 3 as const, code: 'KW', region: 'Middle East' },
    { name: 'Poland', rate: 0.0019, tier: 3 as const, code: 'PL', region: 'Europe' },
    { name: 'Czech Republic', rate: 0.0019, tier: 3 as const, code: 'CZ', region: 'Europe' },
    { name: 'Slovakia', rate: 0.0018, tier: 3 as const, code: 'SK', region: 'Europe' },
    { name: 'Hungary', rate: 0.0018, tier: 3 as const, code: 'HU', region: 'Europe' },
    { name: 'Croatia', rate: 0.0018, tier: 3 as const, code: 'HR', region: 'Europe' },
    { name: 'Slovenia', rate: 0.0018, tier: 3 as const, code: 'SI', region: 'Europe' },

    // --- TIER 4 (LatAm & Developing ~0.0012 - 0.0017) ---
    { name: 'Chile', rate: 0.0016, tier: 4 as const, code: 'CL', region: 'Latin America' },
    { name: 'Uruguay', rate: 0.0016, tier: 4 as const, code: 'UY', region: 'Latin America' },
    { name: 'Romania', rate: 0.0016, tier: 4 as const, code: 'RO', region: 'Europe' },
    { name: 'Bulgaria', rate: 0.0016, tier: 4 as const, code: 'BG', region: 'Europe' },
    { name: 'Serbia', rate: 0.0015, tier: 4 as const, code: 'RS', region: 'Europe' },
    { name: 'Oman', rate: 0.0015, tier: 4 as const, code: 'OM', region: 'Middle East' },
    { name: 'Bahrain', rate: 0.0015, tier: 4 as const, code: 'BH', region: 'Middle East' },
    { name: 'South Africa', rate: 0.0015, tier: 4 as const, code: 'ZA', region: 'Africa' },
    { name: 'Mexico', rate: 0.0014, tier: 4 as const, code: 'MX', region: 'Latin America' },
    { name: 'Colombia', rate: 0.0014, tier: 4 as const, code: 'CO', region: 'Latin America' },
    { name: 'Peru', rate: 0.0014, tier: 4 as const, code: 'PE', region: 'Latin America' },
    { name: 'Ecuador', rate: 0.0014, tier: 4 as const, code: 'EC', region: 'Latin America' },
    { name: 'Costa Rica', rate: 0.0014, tier: 4 as const, code: 'CR', region: 'Latin America' },
    { name: 'Panama', rate: 0.0014, tier: 4 as const, code: 'PA', region: 'Latin America' },
    { name: 'Puerto Rico', rate: 0.0014, tier: 4 as const, code: 'PR', region: 'Latin America' },
    { name: 'Argentina', rate: 0.0013, tier: 4 as const, code: 'AR', region: 'Latin America' },
    { name: 'Brazil', rate: 0.0013, tier: 4 as const, code: 'BR', region: 'Latin America' },
    { name: 'Guatemala', rate: 0.0013, tier: 4 as const, code: 'GT', region: 'Latin America' },
    { name: 'Dominican Republic', rate: 0.0013, tier: 4 as const, code: 'DO', region: 'Latin America' },
    { name: 'Paraguay', rate: 0.0013, tier: 4 as const, code: 'PY', region: 'Latin America' },
    { name: 'Bolivia', rate: 0.0013, tier: 4 as const, code: 'BO', region: 'Latin America' },
    { name: 'El Salvador', rate: 0.0013, tier: 4 as const, code: 'SV', region: 'Latin America' },
    { name: 'Honduras', rate: 0.0013, tier: 4 as const, code: 'HN', region: 'Latin America' },
    { name: 'Nicaragua', rate: 0.0013, tier: 4 as const, code: 'NI', region: 'Latin America' },
    { name: 'Turkey', rate: 0.0012, tier: 4 as const, code: 'TR', region: 'Middle East' },

    // --- TIER 5 (Volume/Emerging < ~0.0012) ---
    { name: 'Philippines', rate: 0.0011, tier: 5 as const, code: 'PH', region: 'Asia' },
    { name: 'Indonesia', rate: 0.0011, tier: 5 as const, code: 'ID', region: 'Asia' },
    { name: 'Thailand', rate: 0.0011, tier: 5 as const, code: 'TH', region: 'Asia' },
    { name: 'Vietnam', rate: 0.0010, tier: 5 as const, code: 'VN', region: 'Asia' },
    { name: 'Malaysia', rate: 0.0010, tier: 5 as const, code: 'MY', region: 'Asia' },
    { name: 'India', rate: 0.0009, tier: 5 as const, code: 'IN', region: 'Asia' },
    { name: 'Pakistan', rate: 0.0008, tier: 5 as const, code: 'PK', region: 'Asia' },
    { name: 'Bangladesh', rate: 0.0008, tier: 5 as const, code: 'BD', region: 'Asia' },
    { name: 'Egypt', rate: 0.0009, tier: 5 as const, code: 'EG', region: 'Africa' },
    { name: 'Morocco', rate: 0.0009, tier: 5 as const, code: 'MA', region: 'Africa' },
    { name: 'Nigeria', rate: 0.0008, tier: 5 as const, code: 'NG', region: 'Africa' },
    { name: 'Kenya', rate: 0.0008, tier: 5 as const, code: 'KE', region: 'Africa' },
    { name: 'Ghana', rate: 0.0008, tier: 5 as const, code: 'GH', region: 'Africa' },
    { name: 'Algeria', rate: 0.0008, tier: 5 as const, code: 'DZ', region: 'Africa' },
    { name: 'Tunisia', rate: 0.0008, tier: 5 as const, code: 'TN', region: 'Africa' },
    { name: 'Ukraine', rate: 0.0009, tier: 5 as const, code: 'UA', region: 'Europe' },
    { name: 'Kazakhstan', rate: 0.0008, tier: 5 as const, code: 'KZ', region: 'Asia' },
    { name: 'Sri Lanka', rate: 0.0008, tier: 5 as const, code: 'LK', region: 'Asia' },
    { name: 'Nepal', rate: 0.0008, tier: 5 as const, code: 'NP', region: 'Asia' },
    { name: 'Venezuela', rate: 0.0008, tier: 5 as const, code: 'VE', region: 'Latin America' },
] satisfies Country[];

export const COLORS: readonly string[] = ['#1DB954', '#1ed760', '#169c46', '#0f7a36', '#535353', '#b3b3b3'];
